[package]
name = "esrgan"
version = "0.1.0"
edition = "2021"
authors = ["Floris @ floris@xylex.ai"]

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.9.0"
serde_json = "1.0.139"
serde_yaml = "0.9.34"
supabase_rs = "0.4.0"
tokio = { version = "1.43.0", features = ["full"] }
