config:
  mirrors:
    ubuntu: https://github.com/floris-xlx/esrgan/releases/download/v0.2.5/realesrgan-ncnn-vulkan-20220424-ubuntu.rar
    windows: https://github.com/floris-xlx/esrgan/releases/download/v0.2.5/realesrgan-ncnn-vulkan-20220424-windows.rar
    macos: https://github.com/floris-xlx/esrgan/releases/download/v0.2.5/realesrgan-ncnn-vulkan-20220424-macos.rar
